apiVersion: v1
kind: PersistentVolume
metadata:
  name: evidently-workspace-storage
spec:
  storageClassName: standard
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/evidently_workspace
    type: DirectoryOrCreate