apiVersion: "serving.kserve.io/v1alpha1"
kind: InferenceGraph 
metadata: 
  name: my-graph1
  namespace: kserve-inference
spec: 
  nodes: 
    ### START CONF HERE
    root:
      routerType: Ensemble
      steps:
        - serviceName: bike-lgbm-1
          name: bike-lgbm-1
        - serviceName: bike-lgbm-2
          name: bike-lgbm-2
    ### END CONF HERE