data:
  prometheus.rules: |-
    groups:
    # An example alerting rule
    - name: Prediction latency alert
      rules:
      - alert: High prediction latency
        expr: histogram_quantile(0.9, rate(revision_app_request_latencies_bucket{isvc_name="wine-quality"}[5m])) > 500
        for: 5s
        labels:
          severity: warning
        annotations:
          summary: High prediction latency

    ### START ALERTING RULE
    - name: 4xx HTTP alert
      rules:
      - alert: 4xx error
        expr: increase(revision_app_request_count{isvc_name="house-price", namespace_name="kserve-inference", response_code_class=~"4.."}[1m]) > 10
        for: 0s
        labels:
          severity: critical
        annotations:
          summary: Many 4xx errors within the last minute
    ### END ALERTING RULE